### ISSUE TITLE
The proxy background

### ISSUE THREAD

**Issue by Reloadandtryagain** [Tacogamerman/Calculator#2]
Hey. Could i have the code for the background of the VOID pro*y. it looks cool.

**Comment by Tacogamerman** [comment]
I don't own void, I just added the calculator and the buttons.

**Comment by ro2alive** [comment]
> Hey. Could i have the code for the background of the VOID pro*y. it looks cool.

It's just the link https://net.cloudranger.net in an iframe with styling. You can also find the code in the `Index.html` file.
