### ISSUE TITLE
Collab!

### ISSUE THREAD

**Issue by Maximus-Weichers** [Tacogamerman/Calculator#4]
Hey, My name is Max I am also a kid in middle school!
I have been following your account for a while so I would like to maybe collaborate on a few things!
Go to strongdog.com(My game's site) You can DM me at Maxy#5430 on discord OR I check more often pushbullet.com I'm maxwick456@gmail.com

**Comment by Tacogamerman** [comment]
Bet bro

**Comment by Maximus-Weichers** [comment]
Awesome! I look forward to working with you! I don't have anything at the moment but I will contact you when I have something! I will add you to my organization!

**Comment by Tacogamerman** [comment]
Ok, see you then.

**Comment by Tacogamerman** [comment]
Btw my discord is Alien_sandwiches17#5692
